# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: stabares <stabares@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/12/04 15:47:57 by stabares          #+#    #+#              #
#    Updated: 2024/12/05 11:45:47 by stabares         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

LIB = ar rcs

RM = rm -fr

CC = gcc

CCFlAGS = -Wall -Werror -Wextra

 
NAME = libft.a

SRC_CHK = ft_isalpha.c \
			ft_isdigit.c \
			ft_isalnum.c \
			ft_isascii.c \
			ft_isprint.c

SRC_STR = ft_strlen.c \
			ft_strlcpy.c \
			ft_strlcat.c \
			ft_strchr.c

SRC_MEM = ft_memset.c   \
			ft_bzero.c  \
			ft_memcpy.c \
			ft_memmove.c

SRC_CH = ft_toupper \
			ft_tolower

SRC = $(SRC_CHK) $(SRC_STR) $(SRC_MEM) $(SRC_CH)
			
